# Generated by Django 3.2.16 on 2023-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='timer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='timer',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
