# Generated by Django 3.2.16 on 2023-08-18 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
