# Generated by Django 3.2.16 on 2023-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_timelog_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
