# Generated by Django 3.2.16 on 2023-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_timelog_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='end',
        ),
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
